spring.application.name=mart

# Database URL
spring.datasource.url=

# Credentials
spring.datasource.username=
spring.datasource.password=

# Driver (optional in new versions but good practice)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
