spring.application.name=mart

# Database URL
spring.datasource.url=jdbc:mysql://localhost:3306/mart?createDatabaseIfNotExist=true

# Credentials
spring.datasource.username=root
spring.datasource.password=Shreyansh@1607

# Driver (optional in new versions but good practice)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
